AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aceface-backend
  
  Sample SAM Template for aceface-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Parameters:
  DBHOST:
    Type: String
    Default: 'host.docker.internal'
  DBPORT:
    Type: String
    Default: '5432'
  DBUSER:
    Type: String
    Default: 'aceface'
  DBPASS:
    Type: String
    Default: 'aceface'
  DBNAME:
    Type: String
    Default: 'postgres'

Resources:
  GetMembersFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: src/lambda/getMembers/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /members
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DB_HOST: !Ref DBHOST
          DB_PORT: !Ref DBPORT
          DB_USER: !Ref DBUSER
          DB_PASS: !Ref DBPASS
          DB_NAME: !Ref DBNAME
  GetMemberFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: src/lambda/getMember/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /members/{uuid}
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DB_HOST: !Ref DBHOST
          DB_PORT: !Ref DBPORT
          DB_USER: !Ref DBUSER
          DB_PASS: !Ref DBPASS
          DB_NAME: !Ref DBNAME

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
