// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Court struct {
	ID          int32
	Uuid        uuid.UUID
	CourtNumber int32
	AltName     pgtype.Text
	Surface     string
	SlotSetID   uuid.UUID
}

type CourtSlotSet struct {
	ID          int32
	Uuid        uuid.UUID
	Name        string
	Description pgtype.Text
	SlotTimes   []byte
}

type Member struct {
	ID         int32
	Uuid       uuid.UUID
	FirstName  string
	LastName   string
	Title      string
	Dob        pgtype.Date
	Email      string
	ProfileUrl pgtype.Text
	CreatedAt  pgtype.Timestamp
}
