// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Member struct {
	ID         int32
	Uuid       uuid.UUID
	FirstName  pgtype.Text
	LastName   pgtype.Text
	Title      pgtype.Text
	Dob        pgtype.Date
	Email      pgtype.Text
	ProfileUrl pgtype.Text
	CreatedAt  pgtype.Timestamp
}
