// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Member struct {
	ID         int32
	Uuid       pgtype.UUID
	FirstName  string
	LastName   string
	Title      string
	Dob        pgtype.Date
	Email      string
	ProfileUrl string
	CreatedAt  pgtype.Timestamp
}
